on:
  pull_request:
    branches: [develop]
  workflow_dispatch:
jobs:
  build:
    runs-on: macOS-latest
    name: "Run Danger"
    steps:
      - uses: actions/checkout@v2
      - name: Install Ruby Dependencies
        run: bundle install --path vendor/bundle
      - name: Run Danger
        run: bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_KEY }}
